# Generated by Django 2.2 on 2021-04-19 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stutus',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
