# Generated by Django 2.2 on 2021-04-19 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_user_stutus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='stutus',
            new_name='status',
        ),
    ]
