# Generated by Django 2.2 on 2021-04-21 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_auto_20210419_2006'),
    ]

    operations = [
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=200)),
                ('sdate', models.DateField(blank=True, null=True)),
                ('track', models.CharField(blank=True, max_length=32, null=True)),
                ('country', models.CharField(blank=True, max_length=32, null=True)),
                ('stime', models.TimeField(blank=True, null=True)),
                ('race_title', models.CharField(blank=True, max_length=200, null=True)),
                ('race_name', models.CharField(blank=True, max_length=100, null=True)),
                ('c1', models.CharField(blank=True, max_length=30, null=True)),
                ('c2', models.CharField(blank=True, max_length=30, null=True)),
                ('c3', models.CharField(blank=True, max_length=30, null=True)),
                ('c4', models.CharField(blank=True, max_length=30, null=True)),
                ('c5', models.CharField(blank=True, max_length=30, null=True)),
                ('c7', models.CharField(blank=True, max_length=30, null=True)),
                ('c8', models.CharField(blank=True, max_length=30, null=True)),
                ('race_class', models.IntegerField(blank=True, null=True)),
                ('marker', models.CharField(blank=True, max_length=15, null=True)),
                ('handicap_rating', models.CharField(blank=True, max_length=15, null=True)),
                ('age_class', models.CharField(blank=True, max_length=15, null=True)),
                ('distance_mls', models.FloatField(blank=True, null=True)),
                ('distance', models.FloatField(blank=True, null=True)),
                ('going', models.CharField(blank=True, max_length=25, null=True)),
                ('prize', models.CharField(blank=True, max_length=150, null=True)),
                ('total_runners', models.IntegerField(blank=True, null=True)),
                ('winning_time', models.FloatField(blank=True, null=True)),
                ('winning_timevar', models.FloatField(blank=True, null=True)),
                ('total_sp', models.IntegerField(blank=True, null=True)),
                ('edate', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ho_racing',
            },
        ),
    ]
