# Generated by Django 2.2 on 2021-04-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_general'),
    ]

    operations = [
        migrations.AddField(
            model_name='general',
            name='c6',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
