# Generated by Django 2.2 on 2021-04-21 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_auto_20210422_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horse',
            name='owner_history',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
