# Generated by Django 2.2 on 2021-04-21 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_auto_20210422_0227'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=200)),
                ('sdate', models.DateField(blank=True, null=True)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('prize_currency', models.CharField(blank=True, max_length=32, null=True)),
                ('prize_money', models.FloatField(blank=True, null=True)),
                ('row_index', models.IntegerField(blank=True, null=True)),
                ('draw', models.IntegerField(blank=True, null=True)),
                ('horse_name', models.CharField(blank=True, max_length=60, null=True)),
                ('horse_country', models.CharField(blank=True, max_length=20, null=True)),
                ('price_decimal', models.FloatField(blank=True, null=True)),
                ('price_fraction', models.CharField(blank=True, max_length=20, null=True)),
                ('price_symbol', models.CharField(blank=True, max_length=20, null=True)),
                ('horse_age', models.IntegerField(blank=True, null=True)),
                ('birth_year', models.IntegerField(blank=True, null=True)),
                ('horse_weight', models.IntegerField(blank=True, null=True)),
                ('dist_upper', models.FloatField(blank=True, null=True)),
                ('dist_beaten', models.FloatField(blank=True, null=True)),
                ('racecard_number', models.IntegerField(blank=True, null=True)),
                ('horse_or', models.IntegerField(blank=True, null=True)),
                ('horse_ts', models.IntegerField(blank=True, null=True)),
                ('horse_rpr', models.IntegerField(blank=True, null=True)),
                ('horse_jockey', models.CharField(blank=True, max_length=80, null=True)),
                ('horse_trainer', models.CharField(blank=True, max_length=80, null=True)),
                ('color', models.CharField(blank=True, max_length=10, null=True)),
                ('sex', models.CharField(blank=True, max_length=10, null=True)),
                ('sire', models.CharField(blank=True, max_length=50, null=True)),
                ('sire_country', models.CharField(blank=True, max_length=10, null=True)),
                ('dam', models.CharField(blank=True, max_length=50, null=True)),
                ('dam_country', models.CharField(blank=True, max_length=50, null=True)),
                ('damsire', models.CharField(blank=True, max_length=50, null=True)),
                ('price_var', models.CharField(blank=True, max_length=50, null=True)),
                ('headgear', models.CharField(blank=True, max_length=8, null=True)),
                ('wind_12', models.CharField(blank=True, max_length=8, null=True)),
                ('horse_link', models.CharField(blank=True, max_length=200, null=True)),
                ('horse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontend.Horse')),
                ('racing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontend.General')),
            ],
            options={
                'db_table': 'ho_player',
            },
        ),
    ]
