# Generated by Django 2.2 on 2021-04-21 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0009_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='general',
            name='prize',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
