# Generated by Django 2.2 on 2021-05-28 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0014_auto_20210430_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='draw_index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
