# Generated by Django 2.2 on 2021-05-28 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0015_player_draw_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='draw_index',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
