# Generated by Django 2.2 on 2021-06-01 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0017_scrapehistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scrapehistory',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='scrapehistory',
            name='active',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
