# Generated by Django 2.2 on 2021-06-01 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0018_auto_20210601_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapehistory',
            name='execute_time',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
