# Generated by Django 2.2 on 2021-06-01 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0019_scrapehistory_execute_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapehistory',
            name='type',
            field=models.CharField(blank=True, default='Automatic', max_length=24, null=True),
        ),
    ]
