# Generated by Django 2.2 on 2021-06-01 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0020_scrapehistory_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapehistory',
            name='execute_time',
        ),
        migrations.AddField(
            model_name='scrapehistory',
            name='end_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
