# Generated by Django 2.2 on 2021-06-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0022_auto_20210601_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapehistory',
            name='end_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
