# Generated by Django 2.2 on 2021-06-01 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0023_auto_20210601_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapehistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
